services:
  app:
    container_name: app-cont
    image: appimage
    ports:
      - '1111:8080'
    depends_on:
      - devopsdb

  devopsdb:
    container_name: devopsdb
    image: dbimage
    ports:
      - '1112:3306'
    volumes:
      - myvolume:/var/lib/mysql/


volumes:
  myvolume:
